<a href="https://colab.research.google.com/github/ZambianZebra/pytorch_tutorial/blob/main/00_Exersizes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
random = torch.rand(7,7)
random

tensor([[0.7214, 0.5760, 0.5702, 0.9525, 0.1348, 0.6708, 0.1280],
        [0.8535, 0.0883, 0.0019, 0.3330, 0.7775, 0.4844, 0.2821],
        [0.5333, 0.6739, 0.4613, 0.5130, 0.5101, 0.7408, 0.0904],
        [0.6281, 0.2486, 0.6641, 0.7193, 0.1299, 0.5418, 0.7742],
        [0.6486, 0.8450, 0.0631, 0.2152, 0.9483, 0.2160, 0.4926],
        [0.4118, 0.5021, 0.4563, 0.1698, 0.0927, 0.2340, 0.7793],
        [0.5549, 0.9139, 0.6552, 0.5219, 0.9591, 0.1945, 0.8203]])

In [2]:
random2 = torch.rand(1,7)
random2

tensor([[0.4930, 0.4325, 0.8153, 0.4478, 0.9049, 0.4797, 0.4282]])

In [3]:
torch.mm(random,random2.T)

tensor([[1.9947],
        [1.6664],
        [2.0159],
        [1.9896],
        [2.0057],
        [1.3981],
        [2.7491]])

In [4]:
torch.manual_seed(0)

torch.matmul(torch.rand(7,7),torch.rand(1,7).T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [5]:
torch.cuda.manual_seed(1234)

In [7]:
torch.manual_seed(1234)
y = torch.rand(2,3)
torch.manual_seed(1234)
x = torch.rand(2,3)
x.to('cuda')
y.to('cuda')

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')

In [9]:
z = torch.matmul(x,y.T)
z

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]])

In [10]:
z.min()

tensor(0.2161)

In [11]:
z.max()

tensor(0.6287)

In [12]:
z.argmax()

tensor(3)

In [13]:
z.argmin()

tensor(1)

In [14]:
torch.manual_seed(7)
v = torch.rand(1,1,1,10)
v, v.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]))

In [16]:
v_new = v.squeeze()
v_new, v_new.shape

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))