<a href="https://colab.research.google.com/github/ZambianZebra/pytorch_tutorial/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("hello this is a test!")

hello this is a test!


In [2]:
import torch
print(torch.__version__)

2.4.1+cu121


 ### Tensors


In [3]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#Matrix
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
#tensor
TENSOR = torch.tensor([[[1,2,4],
                        [4,5,6],
                        [3,7,8]]])
TENSOR

tensor([[[1, 2, 4],
         [4, 5, 6],
         [3, 7, 8]]])

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0, 1, 2]

tensor(6)

###Random tensors


In [16]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3, 3)
random_tensor

tensor([[0.3875, 0.1289, 0.9306],
        [0.2032, 0.8825, 0.7368],
        [0.6328, 0.2066, 0.1437]])

In [17]:
random_tensor.ndim


2

In [18]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape

torch.Size([224, 224, 3])

In [19]:
torch.rand(3,3,3)

tensor([[[0.6431, 0.1078, 0.4741],
         [0.9454, 0.8015, 0.1384],
         [0.9270, 0.7250, 0.9084]],

        [[0.9630, 0.3301, 0.0720],
         [0.9784, 0.1289, 0.6744],
         [0.0579, 0.9960, 0.2144]],

        [[0.8578, 0.5023, 0.1945],
         [0.5688, 0.5356, 0.6399],
         [0.6970, 0.6852, 0.1661]]])

In [20]:
zero = torch.zeros(3,3)
zero

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [21]:
zero*random_tensor


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [22]:
zero.dtype


torch.float32

### Creating a range of tensors and tensors-like


In [23]:
one_ten = torch.arange(start = 1, end = 11, step = 1)
one_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
ten_zeros = torch.zeros_like(input = one_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatype

In [25]:
float_32 = torch.tensor([4.0,16.0,23.0],
                        dtype = None,
                        device = None,
                        requires_grad = False)
float_32


tensor([ 4., 16., 23.])

In [26]:
float_32.dtype

torch.float32

In [27]:
float_16 = float_32.type(torch.half)
float_16

tensor([ 4., 16., 23.], dtype=torch.float16)

In [28]:
tensor_mix = float_16 * float_32
tensor_mix.dtype

torch.float32

In [29]:
int_32 = torch.tensor([4, 56, 4], dtype = torch.int32)
int_32

tensor([ 4, 56,  4], dtype=torch.int32)

In [30]:
int_32*float_32

tensor([ 16., 896.,  92.])

### Getting information from tensors

In [31]:
y = torch.rand([3,4],dtype = torch.half)
y

tensor([[0.4800, 0.0864, 0.4575, 0.6553],
        [0.3594, 0.3032, 0.4268, 0.3892],
        [0.6763, 0.1865, 0.4883, 0.3970]], dtype=torch.float16)

In [32]:
y,y.dtype,y.shape,y.device


(tensor([[0.4800, 0.0864, 0.4575, 0.6553],
         [0.3594, 0.3032, 0.4268, 0.3892],
         [0.6763, 0.1865, 0.4883, 0.3970]], dtype=torch.float16),
 torch.float16,
 torch.Size([3, 4]),
 device(type='cpu'))

### Manipulating tensors

In [33]:
add_tensor = torch.tensor([1,2,3])
add_tensor + 10


tensor([11, 12, 13])

In [36]:
mul_tensor = torch.tensor([1,2,3])
mul_tensor * 10

tensor([10, 20, 30])

In [38]:
sub_tensor = torch.tensor([1,2,3])
sub_tensor - 10

tensor([-9, -8, -7])

In [39]:
torch.add(add_tensor,10)

tensor([11, 12, 13])