<a href="https://colab.research.google.com/github/ZambianZebra/pytorch_tutorial/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("hello this is a test!")

hello this is a test!


In [2]:
import torch
print(torch.__version__)

2.4.1+cu121


 ### Tensors


In [3]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#Matrix
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
#tensor
TENSOR = torch.tensor([[[1,2,4],
                        [4,5,6],
                        [3,7,8]]])
TENSOR

tensor([[[1, 2, 4],
         [4, 5, 6],
         [3, 7, 8]]])

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0, 1, 2]

tensor(6)

###Random tensors


In [16]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3, 3)
random_tensor

tensor([[0.4389, 0.1250, 0.9288],
        [0.0010, 0.2478, 0.2206],
        [0.3222, 0.9022, 0.5493]])

In [17]:
random_tensor.ndim


2

In [18]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape

torch.Size([224, 224, 3])

In [19]:
torch.rand(3,3,3)

tensor([[[0.8009, 0.6101, 0.9008],
         [0.5408, 0.6973, 0.8038],
         [0.1667, 0.4509, 0.1480]],

        [[0.9995, 0.7527, 0.8208],
         [0.2583, 0.4010, 0.3205],
         [0.4984, 0.7040, 0.4006]],

        [[0.1568, 0.6454, 0.8972],
         [0.7904, 0.3455, 0.2980],
         [0.8180, 0.2181, 0.3858]]])

In [20]:
zero = torch.zeros(3,3)
zero

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [21]:
zero*random_tensor


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [22]:
zero.dtype


torch.float32

### Creating a range of tensors and tensors-like


In [23]:
one_ten = torch.arange(start = 1, end = 11, step = 1)
one_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
ten_zeros = torch.zeros_like(input = one_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatype

In [25]:
float_32 = torch.tensor([4.0,16.0,23.0],
                        dtype = None,
                        device = None,
                        requires_grad = False)
float_32


tensor([ 4., 16., 23.])

In [26]:
float_32.dtype

torch.float32

In [27]:
float_16 = float_32.type(torch.half)
float_16

tensor([ 4., 16., 23.], dtype=torch.float16)

In [28]:
tensor_mix = float_16 * float_32
tensor_mix.dtype

torch.float32

In [29]:
int_32 = torch.tensor([4, 56, 4], dtype = torch.int32)
int_32

tensor([ 4, 56,  4], dtype=torch.int32)

In [30]:
int_32*float_32

tensor([ 16., 896.,  92.])

### Getting information from tensors

In [31]:
y = torch.rand([3,4],dtype = torch.half)
y

tensor([[0.6040, 0.4414, 0.2769, 0.4033],
        [0.4526, 0.1333, 0.6206, 0.4683],
        [0.8052, 0.6987, 0.8438, 0.5830]], dtype=torch.float16)

In [32]:
y,y.dtype,y.shape,y.device


(tensor([[0.6040, 0.4414, 0.2769, 0.4033],
         [0.4526, 0.1333, 0.6206, 0.4683],
         [0.8052, 0.6987, 0.8438, 0.5830]], dtype=torch.float16),
 torch.float16,
 torch.Size([3, 4]),
 device(type='cpu'))

### Manipulating tensors

In [33]:
add_tensor = torch.tensor([1,2,3])
add_tensor + 10


tensor([11, 12, 13])

In [34]:
mul_tensor = torch.tensor([1,2,3])
mul_tensor * 10

tensor([10, 20, 30])

In [35]:
sub_tensor = torch.tensor([1,2,3])
sub_tensor - 10

tensor([-9, -8, -7])

In [36]:
torch.add(add_tensor,10)

tensor([11, 12, 13])

### Matrix multiplication

In [37]:
matrix_tensor = torch.tensor([[1,2,3],
                              [4,5,6],
                              [2,4,6]])
mul_tensor = torch.tensor([[7,8,6],
                           [9,10,7],
                           [11,12,9]])
matrix_tensor, mul_tensor

(tensor([[1, 2, 3],
         [4, 5, 6],
         [2, 4, 6]]),
 tensor([[ 7,  8,  6],
         [ 9, 10,  7],
         [11, 12,  9]]))

In [38]:
matrix_tensor[0,0] * mul_tensor[0,0] + matrix_tensor[0,1] * mul_tensor[1,0] + matrix_tensor[0,2] * mul_tensor[2,0]

tensor(58)

In [39]:
%%time
size_tensor = matrix_tensor.size()
print(size_tensor[1])
value = 0
for i in range(size_tensor[1]):
 value += matrix_tensor[0, i] * mul_tensor[i, 0]
 print(value)

3
tensor(7)
tensor(25)
tensor(58)
CPU times: user 4.74 ms, sys: 0 ns, total: 4.74 ms
Wall time: 4.7 ms


In [40]:
%%time
torch.matmul(matrix_tensor, mul_tensor)

CPU times: user 1.64 ms, sys: 0 ns, total: 1.64 ms
Wall time: 5.01 ms


tensor([[ 58,  64,  47],
        [139, 154, 113],
        [116, 128,  94]])

In [41]:
matrix_tensor @ mul_tensor

tensor([[ 58,  64,  47],
        [139, 154, 113],
        [116, 128,  94]])

### Shape errors

In [45]:
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])


In [49]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [50]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [52]:
torch.mm(tensor_A.T, tensor_B)

tensor([[ 76, 103],
        [100, 136]])

### Finding the min, max, mean, sum, etc

In [72]:
x = torch.arange(5,100,15)
x

tensor([ 5, 20, 35, 50, 65, 80, 95])

In [75]:
x.min()

tensor(5)

In [76]:
x.max()

tensor(95)

In [77]:
x.type(torch.float32).mean(), torch.mean(x.type(torch.float32))

(tensor(50.), tensor(50.))

In [78]:
x.sum()

tensor(350)

### Finding positional min and max



In [73]:
x.argmin()

tensor(0)

In [74]:
x.argmax()


tensor(6)