<a href="https://colab.research.google.com/github/ZambianZebra/pytorch_tutorial/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
print("hello this is a test!")

hello this is a test!


In [3]:
import torch
print(torch.__version__)

2.4.1+cu121


 ### Tensors


In [4]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [7]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
#Matrix
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
MATRIX[1]

tensor([ 9, 10])

In [14]:
#tensor
TENSOR = torch.tensor([[[1,2,4],
                        [4,5,6],
                        [3,7,8]]])
TENSOR

tensor([[[1, 2, 4],
         [4, 5, 6],
         [3, 7, 8]]])

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0, 1, 2]

tensor(6)

###Random tensors


In [17]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3, 3)
random_tensor

tensor([[0.6382, 0.6966, 0.0710],
        [0.7596, 0.7994, 0.1316],
        [0.2518, 0.8444, 0.5908]])

In [18]:
random_tensor.ndim


2

In [19]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape

torch.Size([224, 224, 3])

In [20]:
torch.rand(3,3,3)

tensor([[[0.8543, 0.7852, 0.0540],
         [0.3268, 0.4734, 0.2801],
         [0.0872, 0.4486, 0.6468]],

        [[0.5959, 0.8734, 0.7968],
         [0.0558, 0.9579, 0.1641],
         [0.1169, 0.6374, 0.5832]],

        [[0.9339, 0.9539, 0.5109],
         [0.1236, 0.7657, 0.0138],
         [0.3851, 0.5800, 0.7637]]])

In [21]:
zero = torch.zeros(3,3)
zero

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [22]:
zero*random_tensor


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [23]:
zero.dtype


torch.float32

### Creating a range of tensors and tensors-like


In [24]:
one_ten = torch.arange(start = 1, end = 11, step = 1)
one_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
ten_zeros = torch.zeros_like(input = one_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatype

In [26]:
float_32 = torch.tensor([4.0,16.0,23.0],
                        dtype = None,
                        device = None,
                        requires_grad = False)
float_32


tensor([ 4., 16., 23.])

In [27]:
float_32.dtype

torch.float32

In [28]:
float_16 = float_32.type(torch.half)
float_16

tensor([ 4., 16., 23.], dtype=torch.float16)

In [29]:
tensor_mix = float_16 * float_32
tensor_mix.dtype

torch.float32

In [30]:
int_32 = torch.tensor([4, 56, 4], dtype = torch.int32)
int_32

tensor([ 4, 56,  4], dtype=torch.int32)

In [31]:
int_32*float_32

tensor([ 16., 896.,  92.])

### Getting information from tensors

In [32]:
y = torch.rand([3,4],dtype = torch.half)
y

tensor([[0.0420, 0.7910, 0.9160, 0.4507],
        [0.1401, 0.3096, 0.1104, 0.3423],
        [0.1968, 0.1548, 0.4404, 0.9219]], dtype=torch.float16)

In [33]:
y,y.dtype,y.shape,y.device


(tensor([[0.0420, 0.7910, 0.9160, 0.4507],
         [0.1401, 0.3096, 0.1104, 0.3423],
         [0.1968, 0.1548, 0.4404, 0.9219]], dtype=torch.float16),
 torch.float16,
 torch.Size([3, 4]),
 device(type='cpu'))

### Manipulating tensors

In [34]:
add_tensor = torch.tensor([1,2,3])
add_tensor + 10


tensor([11, 12, 13])

In [35]:
mul_tensor = torch.tensor([1,2,3])
mul_tensor * 10

tensor([10, 20, 30])

In [36]:
sub_tensor = torch.tensor([1,2,3])
sub_tensor - 10

tensor([-9, -8, -7])

In [37]:
torch.add(add_tensor,10)

tensor([11, 12, 13])

### Matrix multiplication

In [38]:
matrix_tensor = torch.tensor([[1,2,3],
                              [4,5,6],
                              [2,4,6]])
mul_tensor = torch.tensor([[7,8,6],
                           [9,10,7],
                           [11,12,9]])
matrix_tensor, mul_tensor

(tensor([[1, 2, 3],
         [4, 5, 6],
         [2, 4, 6]]),
 tensor([[ 7,  8,  6],
         [ 9, 10,  7],
         [11, 12,  9]]))

In [39]:
matrix_tensor[0,0] * mul_tensor[0,0] + matrix_tensor[0,1] * mul_tensor[1,0] + matrix_tensor[0,2] * mul_tensor[2,0]

tensor(58)

In [40]:
%%time
size_tensor = matrix_tensor.size()
print(size_tensor[1])
value = 0
for i in range(size_tensor[1]):
 value += matrix_tensor[0, i] * mul_tensor[i, 0]
 print(value)

3
tensor(7)
tensor(25)
tensor(58)
CPU times: user 3.18 ms, sys: 0 ns, total: 3.18 ms
Wall time: 4.26 ms


In [41]:
%%time
torch.matmul(matrix_tensor, mul_tensor)

CPU times: user 489 µs, sys: 93 µs, total: 582 µs
Wall time: 11.6 ms


tensor([[ 58,  64,  47],
        [139, 154, 113],
        [116, 128,  94]])

In [42]:
matrix_tensor @ mul_tensor

tensor([[ 58,  64,  47],
        [139, 154, 113],
        [116, 128,  94]])

### Shape errors

In [43]:
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])


In [44]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [45]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [46]:
torch.mm(tensor_A.T, tensor_B)

tensor([[ 76, 103],
        [100, 136]])

### Finding the min, max, mean, sum, etc

In [47]:
x = torch.arange(5,100,15)
x

tensor([ 5, 20, 35, 50, 65, 80, 95])

In [48]:
x.min()

tensor(5)

In [49]:
x.max()

tensor(95)

In [50]:
x.type(torch.float32).mean(), torch.mean(x.type(torch.float32))

(tensor(50.), tensor(50.))

In [51]:
x.sum()

tensor(350)

### Finding positional min and max



In [52]:
x.argmin()

tensor(0)

In [53]:
x.argmax()


tensor(6)

### Reshaping, stacking, squeezing and unsqueezing tensors

In [54]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [55]:
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [56]:
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [57]:
z[0,0] = 5
x

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [58]:
x_stacked = torch.stack([x,x,x,x], dim = 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [59]:
x_unsqueezed = x.unsqueeze(dim = 0)
x_unsqueezed

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [60]:
x_squeezed = x.squeeze()
x_squeezed

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [61]:
y = torch.zeros(2,1,2,1)
y.shape

torch.Size([2, 1, 2, 1])

In [62]:
y.squeeze().shape

torch.Size([2, 2])

In [63]:
y.unsqueeze(dim = 1).unsqueeze(dim = 2).shape

torch.Size([2, 1, 1, 1, 2, 1])

In [64]:
torch.permute(y, (2,0,1,3)).shape

torch.Size([2, 2, 1, 1])

In [65]:
x_original = torch.rand(size = (224,224,3))
x_original.shape

torch.Size([224, 224, 3])

In [66]:
x_permuted = x_original.permute(2,0,1)
x_permuted.shape

torch.Size([3, 224, 224])

In [67]:
x_original[0,0,0] = 728218
x_original[0,0,0], x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))

### Selecting data (indexing)

In [68]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [69]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [70]:
x[0, 0]

tensor([1, 2, 3])

In [71]:
x[0, 2, 2]

tensor(9)

In [72]:
x[:, 0]

tensor([[1, 2, 3]])

In [73]:
x[:,0]

tensor([[1, 2, 3]])

### Pytorch tensors and numpy

In [75]:
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [76]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [77]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility

In [81]:
torch.rand(3,3)

tensor([[0.3101, 0.3731, 0.2337],
        [0.7129, 0.1639, 0.9486],
        [0.6721, 0.4267, 0.9857]])

In [99]:
random_A = torch.rand(3,4)
random_B = torch.rand(3,4)
print(random_A)
print(random_B)
print(random_A == random_B)

tensor([[0.0329, 0.5702, 0.4687, 0.0907],
        [0.6216, 0.9962, 0.5078, 0.9521],
        [0.8056, 0.6341, 0.1258, 0.0245]])
tensor([[0.6833, 0.4934, 0.2576, 0.2399],
        [0.9787, 0.4141, 0.3780, 0.6605],
        [0.4337, 0.9245, 0.6607, 0.9719]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [105]:
RANDOM_SEED = 56
torch.manual_seed(RANDOM_SEED)
random_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_D = torch.rand(3,4)
print(random_C)
print(random_D)
print(random_C == random_D)

tensor([[0.9531, 0.5607, 0.3535, 0.9455],
        [0.4676, 0.7281, 0.2759, 0.4734],
        [0.7383, 0.5281, 0.2217, 0.7745]])
tensor([[0.9531, 0.5607, 0.3535, 0.9455],
        [0.4676, 0.7281, 0.2759, 0.4734],
        [0.7383, 0.5281, 0.2217, 0.7745]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Accessing a GPU

In [106]:
!nvidia-smi

Wed Sep 25 12:40:57 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   39C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [107]:
torch.cuda.is_available()

True

In [108]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [109]:
torch.cuda.device_count()


1

In [110]:
tensor = torch.tensor([1,2,3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [112]:
tensor_gpu = tensor.to(device)
tensor_gpu

tensor([1, 2, 3], device='cuda:0')

In [118]:
tensor_cpu = tensor_gpu.cpu().numpy()
tensor_cpu

array([1, 2, 3])