<a href="https://colab.research.google.com/github/ZambianZebra/pytorch_tutorial/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("hello this is a test!")

hello this is a test!


In [2]:
import torch
print(torch.__version__)

2.4.1+cu121


 ### Tensors


In [3]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [7]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [11]:
#Matrix
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
MATRIX[1]

tensor([ 9, 10])

In [16]:
#tensor
TENSOR = torch.tensor([[[1,2,4],
                        [4,5,6],
                        [3,7,8]]])
TENSOR

tensor([[[1, 2, 4],
         [4, 5, 6],
         [3, 7, 8]]])

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [23]:
TENSOR[0, 1, 2]

tensor(6)

###Random tensors


In [42]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3, 3)
random_tensor

tensor([[0.7203, 0.5910, 0.0893],
        [0.0448, 0.3768, 0.7837],
        [0.7997, 0.2502, 0.9919]])

In [43]:
random_tensor.ndim


2

In [45]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape

torch.Size([224, 224, 3])

In [47]:
torch.rand(3,3,3)

tensor([[[0.1832, 0.9991, 0.5486],
         [0.6888, 0.9966, 0.3923],
         [0.0770, 0.0880, 0.0606]],

        [[0.9246, 0.5406, 0.8027],
         [0.0662, 0.9970, 0.3334],
         [0.5853, 0.8108, 0.5799]],

        [[0.9143, 0.8961, 0.2684],
         [0.4672, 0.9482, 0.2816],
         [0.6351, 0.8262, 0.6224]]])

In [48]:
zero = torch.zeros(3,3)
zero

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [49]:
zero*random_tensor


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [50]:
zero.dtype


torch.float32

### Creating a range of tensors and tensors-like


In [54]:
one_ten = torch.arange(start = 1, end = 11, step = 1)
one_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
ten_zeros = torch.zeros_like(input = one_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatype

In [57]:
float_32 = torch.tensor([4.0,16.0,23.0],
                        dtype = None,
                        device = None,
                        requires_grad = False)
float_32


tensor([ 4., 16., 23.])

In [58]:
float_32.dtype

torch.float32